services:
  mongodb:
    image: mongo:7.0
    volumes:
      - mongo-data:/data/db
      # - ./.database/mongo_backup:/data/backup  # take backup files
    healthcheck:
      test: ["CMD-SHELL", "mongosh", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - app-network
    expose:
      - "27017"
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}
      - MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}

  express:
    build:
      context: ./express/tourist_project
      dockerfile: Dockerfile
    environment:
      - NODE_ENV=development
      - MONGO_HOST=mongodb
      - MONGO_LINK=${MONGO_LINK}
      - HASH_SALT=${HASH_SALT}
      - JWT_SECRET=${JWT_SECRET}
      - RABBIT_LINK_CONNECT=${RABBIT_LINK_CONNECT}
      - FINAL_HOST=${FINAL_HOST}
    expose:
      - "3000"
    volumes:
      - ./express/tourist_project:/tourist_project
      - /tourist_project/node_modules
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - app-network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 10s
      timeout: 5s
      retries: 5
    # restart: unless-stopped
    container_name: education-express-1

  nginx:
    container_name: education-nginx-1
    image: nginx:1.27
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/public:/public:ro
    depends_on:
      express:
        condition: service_healthy
      # flask:
      #   condition: service_healthy
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost"]
      interval: 10s
      timeout: 5s 
      retries: 5
    networks:
      - app-network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

networks:
  app-network:
    driver: bridge

volumes:
  mongo-data: